use std::path::PathBuf;
use std::sync::Arc;

use codex_protocol::models::ActivePermissionProfile;
use codex_protocol::models::PermissionProfile;
use codex_protocol::models::ShellCommandToolCallParams;
use codex_protocol::protocol::SkillScope;
use pretty_assertions::assert_eq;

use crate::config::PermissionProfileSnapshot;
use crate::exec_env::CODEX_PERMISSION_PROFILE_ENV_VAR;
use crate::exec_env::create_env;
use crate::exec_env::inject_permission_profile_env;
use crate::exec_env::inject_session_id_env;
use crate::sandboxing::SandboxPermissions;
use crate::session::step_context::StepContext;
use crate::session::tests::make_session_and_context;
use crate::session::turn_context::TurnEnvironment;
use crate::session::turn_context::TurnEnvironmentConfig;
use crate::shell::Shell;
use crate::shell::ShellType;
use crate::skills::skill_activation_snapshot;
use crate::skills::tests::assert_implicit_skill_candidate;
use crate::skills::tests::configure_implicit_skill_fixture_for_exec;
use crate::skills::tests::implicit_skill_fixture;
use crate::skills::tests::quote_skill_test_path;
use crate::tools::context::FunctionToolOutput;
use crate::tools::context::ToolCallSource;
use crate::tools::context::ToolInvocation;
use crate::tools::context::ToolPayload;
use crate::tools::handlers::ShellCommandHandler;
use crate::tools::hook_names::HookToolName;
use crate::tools::registry::CoreToolRuntime;
use crate::tools::registry::ToolExecutor;
use crate::turn_diff_tracker::TurnDiffTracker;
use codex_shell_command::is_safe_command::is_known_safe_command;
use codex_shell_command::powershell::try_find_powershell_executable_blocking;
use codex_shell_command::powershell::try_find_pwsh_executable_blocking;
use codex_utils_path_uri::PathUri;
use serde_json::json;
use tokio::sync::Mutex;

/// The logic for is_known_safe_command() has heuristics for known shells,
/// so we must ensure the commands generated by [ShellCommandHandler] can be
/// recognized as safe if the `command` is safe.
#[test]
fn commands_generated_by_shell_command_handler_can_be_matched_by_is_known_safe_command() {
    let bash_shell = Shell {
        shell_type: ShellType::Bash,
        shell_path: PathBuf::from("/bin/bash"),
    };
    assert_safe(&bash_shell, "ls -la");

    let zsh_shell = Shell {
        shell_type: ShellType::Zsh,
        shell_path: PathBuf::from("/bin/zsh"),
    };
    assert_safe(&zsh_shell, "ls -la");

    if let Some(path) = try_find_powershell_executable_blocking() {
        let powershell = Shell {
            shell_type: ShellType::PowerShell,
            shell_path: path.to_path_buf(),
        };
        assert_safe(&powershell, "ls -Name");
    }

    if let Some(path) = try_find_pwsh_executable_blocking() {
        let pwsh = Shell {
            shell_type: ShellType::PowerShell,
            shell_path: path.to_path_buf(),
        };
        assert_safe(&pwsh, "ls -Name");
    }
}

fn assert_safe(shell: &Shell, command: &str) {
    assert!(is_known_safe_command(&shell.derive_exec_args(
        command, /* use_login_shell */ /*use_login_shell*/ true
    )));
    assert!(is_known_safe_command(&shell.derive_exec_args(
        command, /* use_login_shell */ /*use_login_shell*/ false
    )));
}

#[tokio::test]
async fn shell_command_handler_to_exec_params_uses_selected_environment() {
    let (session, mut turn_context) = make_session_and_context().await;
    let permission_profile = turn_context.config.permissions.permission_profile().clone();
    Arc::make_mut(&mut turn_context.config)
        .permissions
        .set_permission_profile_from_session_snapshot(PermissionProfileSnapshot::active(
            permission_profile.clone(),
            ActivePermissionProfile::new("thread-profile"),
        ))
        .expect("set active permission profile");

    let command = "echo hello".to_string();
    let workdir = Some("subdir".to_string());
    let login = None;
    let timeout_ms = Some(1234);
    let sandbox_permissions = SandboxPermissions::RequireEscalated;
    let justification = Some("because tests".to_string());

    let selected_shell = Shell {
        shell_type: ShellType::Bash,
        shell_path: PathBuf::from("/selected/bin/bash"),
    };
    let expected_command = selected_shell.derive_exec_args(&command, /*use_login_shell*/ true);
    let selected_cwd = turn_context.config.cwd.join("selected-environment");
    let expected_cwd = selected_cwd.join("subdir");
    let active_permission_profile = ActivePermissionProfile::new("selected-profile");
    let selected_environment = TurnEnvironment::new(
        "selected-environment".to_string(),
        Arc::clone(
            &turn_context
                .environments
                .primary()
                .expect("primary environment")
                .environment,
        ),
        PathUri::from_abs_path(&selected_cwd),
        Vec::new(),
        Some(selected_shell),
        TurnEnvironmentConfig {
            allow_login_shell: true,
            permission_profile: PermissionProfileSnapshot::active(
                permission_profile,
                active_permission_profile.clone(),
            ),
            selected_capability_roots: None,
        },
    );
    let mut expected_env = create_env(
        &turn_context.config.permissions.shell_environment_policy,
        Some(session.thread_id),
    );
    inject_session_id_env(&mut expected_env, session.session_id());
    inject_permission_profile_env(&mut expected_env, Some(&active_permission_profile));

    let params = ShellCommandToolCallParams {
        command,
        workdir,
        login,
        timeout_ms,
        sandbox_permissions: Some(sandbox_permissions),
        additional_permissions: None,
        prefix_rule: None,
        justification: justification.clone(),
    };

    let exec_params = ShellCommandHandler::to_exec_params(
        &params,
        &session,
        &turn_context,
        &selected_environment,
        expected_cwd.clone(),
    )
    .expect("login shells should be allowed");

    // ExecParams cannot derive Eq due to the CancellationToken field, so we manually compare the fields.
    assert_eq!(exec_params.command, expected_command);
    assert_eq!(exec_params.cwd, expected_cwd);
    assert_eq!(exec_params.env, expected_env);
    assert_eq!(
        exec_params.env.get(CODEX_PERMISSION_PROFILE_ENV_VAR),
        Some(&active_permission_profile.id)
    );
    assert_eq!(exec_params.network, turn_context.network);
    assert_eq!(
        exec_params.network_environment_id.as_deref(),
        Some("selected-environment")
    );
    assert_eq!(exec_params.expiration.timeout_ms(), timeout_ms);
    assert_eq!(exec_params.sandbox_permissions, sandbox_permissions);
    assert_eq!(exec_params.justification, justification);
    assert_eq!(exec_params.arg0, None);
}

#[test]
fn shell_command_handler_respects_explicit_login_flag() {
    let shell = Shell {
        shell_type: ShellType::Bash,
        shell_path: PathBuf::from("/bin/bash"),
    };

    let login_command = ShellCommandHandler::base_command(
        &shell,
        "echo login shell",
        /*use_login_shell*/ true,
    );
    assert_eq!(
        login_command,
        shell.derive_exec_args("echo login shell", /*use_login_shell*/ true)
    );

    let non_login_command = ShellCommandHandler::base_command(
        &shell,
        "echo non login shell",
        /*use_login_shell*/ false,
    );
    assert_eq!(
        non_login_command,
        shell.derive_exec_args("echo non login shell", /*use_login_shell*/ false)
    );
}

#[tokio::test]
async fn shell_command_handler_defaults_to_non_login_when_disallowed() {
    let (session, turn_context) = make_session_and_context().await;
    let mut turn_environment = turn_context
        .environments
        .primary()
        .expect("primary environment")
        .clone();
    turn_environment.config.allow_login_shell = false;
    let cwd = turn_environment
        .cwd()
        .to_abs_path()
        .expect("native environment cwd");
    let params = ShellCommandToolCallParams {
        command: "echo hello".to_string(),
        workdir: None,
        login: None,
        timeout_ms: None,
        sandbox_permissions: None,
        additional_permissions: None,
        prefix_rule: None,
        justification: None,
    };

    let exec_params = ShellCommandHandler::to_exec_params(
        &params,
        &session,
        &turn_context,
        &turn_environment,
        cwd,
    )
    .expect("non-login shells should still be allowed");

    assert_eq!(
        exec_params.command,
        session
            .user_shell()
            .derive_exec_args("echo hello", /*use_login_shell*/ false)
    );
}

#[tokio::test]
async fn shell_command_handler_rejects_justification_without_sandbox_permissions() {
    let (session, turn_context) = make_session_and_context().await;
    let turn_environment = turn_context
        .environments
        .primary()
        .expect("primary environment");
    let cwd = turn_environment
        .cwd()
        .to_abs_path()
        .expect("native environment cwd");
    let params = ShellCommandToolCallParams {
        command: "echo hello".to_string(),
        workdir: None,
        login: None,
        timeout_ms: None,
        sandbox_permissions: None,
        additional_permissions: None,
        prefix_rule: None,
        justification: Some("Allow this command".to_string()),
    };

    let err = ShellCommandHandler::to_exec_params(
        &params,
        &session,
        &turn_context,
        turn_environment,
        cwd,
    )
    .expect_err("justification without sandbox permissions should be rejected");

    assert!(
        err.to_string()
            .contains("`justification` requires an explicit `sandbox_permissions`"),
        "unexpected error: {err}"
    );
}

#[test]
fn shell_command_handler_rejects_login_when_disallowed() {
    let err =
        ShellCommandHandler::resolve_use_login_shell(Some(true), /*allow_login_shell*/ false)
            .expect_err("explicit login should be rejected");

    assert!(
        err.to_string()
            .contains("login shell is disabled by config"),
        "unexpected error: {err}"
    );
}

#[tokio::test]
async fn shell_command_pre_tool_use_payload_uses_raw_command() {
    let payload = ToolPayload::Function {
        arguments: json!({ "command": "printf shell command" }).to_string(),
    };
    let (session, turn) = make_session_and_context().await;
    let turn = Arc::new(turn);
    let handler = ShellCommandHandler::from(codex_tools::ShellCommandBackendConfig::Classic);

    assert_eq!(
        handler.pre_tool_use_payload(&ToolInvocation {
            session: session.into(),
            step_context: StepContext::for_test(Arc::clone(&turn)),
            turn,
            cancellation_token: tokio_util::sync::CancellationToken::new(),
            tracker: Arc::new(Mutex::new(TurnDiffTracker::new())),
            call_id: "call-42".to_string(),
            tool_name: codex_tools::ToolName::plain("shell_command"),
            source: crate::tools::context::ToolCallSource::Direct,
            payload,
        }),
        Some(crate::tools::registry::PreToolUsePayload {
            tool_name: HookToolName::bash(),
            tool_input: json!({ "command": "printf shell command" }),
        })
    );
}

#[tokio::test]
async fn build_post_tool_use_payload_uses_tool_output_wire_value() {
    let payload = ToolPayload::Function {
        arguments: json!({ "command": "printf shell command" }).to_string(),
    };
    let output = FunctionToolOutput {
        body: vec![],
        success: Some(true),
        post_tool_use_response: Some(json!("shell output")),
    };
    let handler = ShellCommandHandler::from(codex_tools::ShellCommandBackendConfig::Classic);
    let (session, turn) = make_session_and_context().await;
    let turn = Arc::new(turn);
    let invocation = ToolInvocation {
        session: session.into(),
        step_context: StepContext::for_test(Arc::clone(&turn)),
        turn,
        cancellation_token: tokio_util::sync::CancellationToken::new(),
        tracker: Arc::new(Mutex::new(TurnDiffTracker::new())),
        call_id: "call-42".to_string(),
        tool_name: codex_tools::ToolName::plain("shell_command"),
        source: ToolCallSource::Direct,
        payload,
    };
    assert_eq!(
        handler.post_tool_use_payload(&invocation, &output),
        Some(crate::tools::registry::PostToolUsePayload {
            tool_name: HookToolName::bash(),
            tool_use_id: "call-42".to_string(),
            tool_input: json!({ "command": "printf shell command" }),
            tool_response: json!("shell output"),
        })
    );
}

#[tokio::test]
async fn classic_shell_implicit_skill_activation_actual_nonzero_does_not_record() {
    let mut fixture = implicit_skill_fixture(SkillScope::Repo).await;
    configure_implicit_skill_fixture_for_exec(&mut fixture, PermissionProfile::Disabled);
    let command = format!(
        "cat {} ; exit 9",
        quote_skill_test_path(&fixture.skill_path)
    );
    assert_implicit_skill_candidate(&fixture, &command).await;
    let turn = Arc::new(fixture.turn);
    let invocation = classic_shell_invocation(
        Arc::new(fixture.session),
        Arc::clone(&turn),
        &command,
        "failed-skill-read",
    );

    let Err(error) = ShellCommandHandler::from(codex_tools::ShellCommandBackendConfig::Classic)
        .handle(invocation)
        .await
    else {
        panic!("classic nonzero shell exit should be returned to the model as an error");
    };

    assert!(error.to_string().contains("Exit code: 9"));
    // This assertion happens in a fresh turn, before any successful read can
    // insert an equal activation and mask a false positive in the set.
    assert_eq!(skill_activation_snapshot(&turn), Vec::new());
}

#[tokio::test]
async fn classic_shell_implicit_skill_activation_actual_escalation_rejection_does_not_record() {
    let mut fixture = implicit_skill_fixture(SkillScope::System).await;
    configure_implicit_skill_fixture_for_exec(&mut fixture, PermissionProfile::Disabled);
    let command = format!("cat {}", quote_skill_test_path(&fixture.skill_path));
    assert_implicit_skill_candidate(&fixture, &command).await;
    let turn = Arc::new(fixture.turn);
    let invocation = ToolInvocation {
        payload: ToolPayload::Function {
            arguments: json!({
                "command": command,
                "sandbox_permissions": "require_escalated",
                "justification": "exercise approval rejection"
            })
            .to_string(),
        },
        ..classic_shell_invocation(
            Arc::new(fixture.session),
            Arc::clone(&turn),
            "true",
            "denied-skill-read",
        )
    };

    let Err(error) = ShellCommandHandler::from(codex_tools::ShellCommandBackendConfig::Classic)
        .handle(invocation)
        .await
    else {
        panic!("Never policy must reject explicit escalation");
    };

    assert!(error.to_string().contains("approval policy is Never"));
    assert_eq!(skill_activation_snapshot(&turn), Vec::new());
}

#[tokio::test]
async fn classic_shell_implicit_skill_activation_actual_sandbox_denial_does_not_record() {
    let mut fixture = implicit_skill_fixture(SkillScope::Repo).await;
    configure_implicit_skill_fixture_for_exec(&mut fixture, PermissionProfile::read_only());
    let denied_path = fixture.workdir.join("sandbox-denied.txt");
    let command = format!(
        "cat {} ; echo denied > {}",
        quote_skill_test_path(&fixture.skill_path),
        quote_skill_test_path(&denied_path)
    );
    assert_implicit_skill_candidate(&fixture, &command).await;
    let turn = Arc::new(fixture.turn);

    let Err(error) = ShellCommandHandler::from(codex_tools::ShellCommandBackendConfig::Classic)
        .handle(classic_shell_invocation(
            Arc::new(fixture.session),
            Arc::clone(&turn),
            &command,
            "sandbox-denied-skill-read",
        ))
        .await
    else {
        panic!("classic sandbox denial should be returned to the model as an error");
    };
    let message = error.to_string().to_ascii_lowercase();

    assert!(
        message.contains("permission denied")
            || message.contains("operation not permitted")
            || message.contains("read-only file system")
            || message.contains("sandbox"),
        "unexpected sandbox-denial output: {message}"
    );
    assert!(!denied_path.exists());
    assert_eq!(skill_activation_snapshot(&turn), Vec::new());
}

#[tokio::test]
async fn classic_shell_implicit_skill_activation_actual_apply_patch_intercept_does_not_record() {
    let mut fixture = implicit_skill_fixture(SkillScope::Repo).await;
    configure_implicit_skill_fixture_for_exec(&mut fixture, PermissionProfile::Disabled);
    let patch_dir = tempfile::tempdir_in(&fixture.turn.config.cwd)
        .expect("create patch directory inside session workspace");
    let workdir = patch_dir.path().to_path_buf();
    let command = "apply_patch <<'PATCH'\n*** Begin Patch\n*** Add File: intercepted.txt\n+intercepted\n*** End Patch\nPATCH";
    let turn = Arc::new(fixture.turn);
    let invocation = ToolInvocation {
        payload: ToolPayload::Function {
            arguments: json!({ "command": command, "workdir": workdir }).to_string(),
        },
        ..classic_shell_invocation(
            Arc::new(fixture.session),
            Arc::clone(&turn),
            "true",
            "intercepted-apply-patch",
        )
    };

    ShellCommandHandler::from(codex_tools::ShellCommandBackendConfig::Classic)
        .handle(invocation)
        .await
        .expect("pure apply_patch should be intercepted successfully");

    assert_eq!(
        std::fs::read_to_string(workdir.join("intercepted.txt"))
            .expect("intercept should create patched file"),
        "intercepted\n"
    );
    // The interceptor only accepts a pure apply_patch command, while implicit
    // activation requires a skill read/run in that same command. Those input
    // shapes cannot overlap, so the actual handler is the closest valid seam.
    assert_eq!(skill_activation_snapshot(&turn), Vec::new());
}

fn classic_shell_invocation(
    session: Arc<crate::session::session::Session>,
    turn: Arc<crate::session::turn_context::TurnContext>,
    command: &str,
    call_id: &str,
) -> ToolInvocation {
    ToolInvocation {
        session,
        step_context: StepContext::for_test(Arc::clone(&turn)),
        turn,
        cancellation_token: tokio_util::sync::CancellationToken::new(),
        tracker: Arc::new(Mutex::new(TurnDiffTracker::new())),
        call_id: call_id.to_string(),
        tool_name: codex_tools::ToolName::plain("shell_command"),
        source: ToolCallSource::Direct,
        payload: ToolPayload::Function {
            arguments: json!({ "command": command }).to_string(),
        },
    }
}
